### ISSUE TITLE
Computed values lost in switch context?

### ISSUE THREAD

**Issue by potens1** [construct/construct#357] opened 2017-05-31 20:05 UTC
Is there a reason Computed values are lost while building a Switch Struct ?

Here are two versions of code that should do the same thing (more or less)
```
inner = Struct(
    "cpted"/ Computed(lambda ctx: 4),
    Probe(), 
    "baz" / Byte)

bar = Struct(
    "dsc" / Byte,
    "foo" / inner,
    Probe()
)

bar2 = Struct(
    "dsc" / Byte,
    "foo" / Switch(this.dsc, {'1': inner}, inner),
    Probe()
)

```

But, while building, the behaviour is different, the Computed field is available when there is no Switch, but is not when Switch is in use. Is that something wanted ?

If you wonder why I need that, it's the only I have right now to be able to get the size of "inner" (in example), but, while building, this is not available anymore.

## Output

```
In [59]: bar2.build(dict(dsc=2, foo=dict(baz=1)))
================================================================================
Probe <unnamed 23>
path is building -> foo, func is None
EOF reached
Container: 
    baz = 1
    cpted = 4
================================================================================
================================================================================
Probe <unnamed 25>
path is building, func is None
EOF reached
Container: 
    dsc = 2
    foo = {'baz': 1}
================================================================================
Out[59]: b'\x02\x01'

In [60]: bar.build(dict(dsc=2, foo=dict(baz=1)))
================================================================================
Probe <unnamed 23>
path is building -> foo, func is None
EOF reached
Container: 
    baz = 1
    cpted = 4
================================================================================
================================================================================
Probe <unnamed 24>
path is building, func is None
EOF reached
Container: 
    dsc = 2
    foo = Container: 
        baz = 1
        cpted = 4
================================================================================
Out[60]: b'\x02\x01'
```

**Comment by arekbulski** [comment] 2017-05-31 21:30
`this.dsc` would be equal integer 1 and not  a b-string "1".

**Comment by potens1** [comment] 2017-05-31 21:44
Hi,
Thanks for the answer.
This was a quick example about missing `cpted` in the context of bar2 but present in bar.

**Comment by arekbulski** [comment] 2017-05-31 21:55
You dont have to break the code apart, you can inline like `If(this.dsc==1, Struct(...))` and also, use `Compued(4)` no need for lambda.

**Comment by potens1** [comment] 2017-05-31 22:10
Sorry,
It's a reduced version of the other question (that I'm answering) where you can have at least 20 different values (so I thought about switch and not 20 IfThenElse If), same with the lambda, I did not adapt enough, but it is because I've put 4 to have something while in my real case, it should be the computed length with computation that can be different for the 20 cases.

**Comment by arekbulski** [comment] 2017-06-01 22:20
Aside of your code being so contrived, I confirm that you indeed found a bug. I am not sure if the problem is in `Struct or Switch` but the context is missing entries indeed. Test case added. I cannot tell you when and if a fix will be released yet. I do not know what is wrong is the code.

**Comment by potens1** [comment] 2017-06-01 22:38
I'll try to isolate the case tomorrow (want to be able to at least have something working before going to sleep, and it's already 00.30). I don't need it anymore since I'm doing Tell et al, so no hurry for me on that specific point.

**Comment by potens1** [comment] 2017-06-02 16:53
In fact, it's not that the context does not have all the values, the problem seems to be Switch returns a dict, not a Container (while have a look later today)

**Comment by arekbulski** [comment] 2017-06-02 19:14
Context contains save objects that were passed to build(), unless a class returns something to override it. Since you put dict then you are given a dict back?
` bar2.build(dict(dsc=2, foo=dict(baz=1)))`

**Comment by arekbulski** [comment] 2017-06-02 19:23
Test case shows that computed value is present in the context regardless of Switch. I can no longer consider this a bug.... perhaps some sort of quirk.

**Comment by potens1** [comment] 2017-06-02 19:57
I don't get it.

This is *not* working
```python
inner = Struct(
    "computed" / Computed(4),
)
st = Struct(
    "a" / inner,
    "b" / Switch(5, {}, inner),
    Probe(),
    Check(this.a.computed == 4),
    Check(this.b.computed == 4),
)
st.parse(b"")
```

But, even if it should do the exact same thing, this *is* working:
```python
inner = Struct(
    "computed" / Computed(4),
)
st = Struct(
    "a" / inner,
    "b" / Switch(5, {1: inner}, inner),
    Probe(),
    Check(this.a.computed == 4),
    Check(this.b.computed == 4),
)
st.parse(b"")
```

**Comment by potens1** [comment] 2017-06-02 20:10
This can show the different behaviors:

```python
from construct import *

inner = Struct(
    "computed" / Computed(4),
)

inner2 = Struct(
    "computed" / Computed(7),
)

st1 = Struct(
    "a" / inner,
    "b" / Switch(5, {1: inner2}, inner),
    Probe(),
)

st2 = Struct(
    "a" / inner,
    "b" / Switch(5, {}, inner),
    Probe(),
)
assert st1.parse(b"") == st2.parse(b"")
```

```
================================================================================
Probe <unnamed 1>
path is parsing, func is None
EOF reached
Container: 
    a = Container: 
        computed = 4
    b = Container: 
        computed = 4
================================================================================
================================================================================
Probe <unnamed 2>
path is parsing, func is None
EOF reached
Container: 
    a = Container: 
        computed = 4
    computed = 4
================================================================================
Traceback (most recent call last):
  File "baz4.py", line 22, in <module>
    assert st1.parse(b"") == st2.parse(b"")
AssertionError
```

**Comment by arekbulski** [comment] 2017-06-02 22:49
Thank you for pointing this example out (in the future,  you could have sent it as PR). I admit this is strange, lets call it... fleeting bug.

**Comment by hardkrash** [comment] 2017-06-09 06:41
@potens1 Does https://github.com/hardkrash/construct/tree/feature/fix_switch_357_take_2 fix your issue?

**Comment by potens1** [comment] 2017-06-12 20:21
@hardkrash Indeed, take_2 seems to solve it

**Comment by arekbulski** [comment] 2017-08-28 19:10
I am going to deny Embedded Switch patches (for reasons described in their tickets) so I close this bug report, without fixing it, simply because I dont understand how or why it does not work. I just hope noone in the future is going to find this bug again.

**Comment by hardkrash** [comment] 2017-08-29 04:21
The problem is that the `Switch`'s `__init__` method only inspects `cases` for the flags and ignores `default`'s flags.

In `st1` the statement `Switch(5, {1: inner2}, inner)` has `cases` as a dictionary with one item of `{1: inner2}` and `default` as `inner`

In `st2` the statement `Switch(5, {}, inner)` has `cases` as an empty dictionary `{}` and `default` as `inner1`

Since `default` is ignored these flags are incorrect for `st2`
`st1` is only correct because `inner` and `inner2` have **identical** flags.  It will have unexpected consequences if they differ.

```
    def __init__(self, keyfunc, cases, default=NoDefault, includekey=False):
        super(Switch, self).__init__()
        self.keyfunc = keyfunc
        self.cases = cases
        self.default = default
        self.includekey = includekey
        self.flagbuildnone = all(sc.flagbuildnone for sc in cases.values() if sc is not Pass)
        self.flagembedded = all(sc.flagembedded for sc in cases.values() if sc is not Pass)
```

This should be changed to include `default` if set.

```
    def __init__(self, keyfunc, cases, default=NoDefault, includekey=False):
        super(Switch, self).__init__()
        self.keyfunc = keyfunc
        self.cases = cases
        self.default = default
        self.includekey = includekey
        all_cases = list(cases.values())  # Collect cases except Pass subconstructs.
        if default is not self.NoDefault:
            all_cases.append(default)  # Add default if it was passed in.
        self.flagbuildnone = all(sc.flagbuildnone for sc in all_cases if sc is not Pass)
        self.flagembedded = all(sc.flagembedded for sc in all_cases if sc is not Pass)
```

**Comment by hardkrash** [comment] 2017-08-29 04:26
Note, to make `If` work flags must ignore `Pass`.

**Comment by arekbulski** [comment] 2017-08-29 15:59
Thank you for explanation, it clarified it totally. I can accept this much.

**Comment by arekbulski** [comment] 2017-08-29 16:01
I skipped filtering out Pass and test cases passes just fine without it.

**Closed** 2017-08-30 05:25 UTC
Labels: bug found
