### ISSUE TITLE
Compiling is very slow

### ISSUE THREAD

**Issue by Schamper** [construct/construct#688] opened 2018-03-13 21:24 UTC
Compiling seems to be awfully slow. Every time I run tests, or start a script related to my application I need to wait 4-5 seconds before it will actually start. 

Earlier versions of the compiler were way faster (I didn't check what exactly changed, I only know that now files are involved). Are there plans to address this?

**Comment by Schamper** [comment] 2018-03-13 21:57
For example, why not something like:
```
module = imp.new_module(modulename)
c = compile(source, '<string>', 'exec')
exec(c, module.__dict__)
```

Seems to work in my limited testing.

**Comment by arekbulski** [comment] 2018-03-13 22:18
The first versions of the compiler produced pure-python code, so importing was instant. Then I added cython so importing some examples in core testsuite took up to a minute. You should pip upgrade. Newest version doesnt use cython, so it should not have the issue either. Does this problem still exist with newest version? If so, please show me the code in question?

Also... you can use pypy to make the parsers run faster, not sure about importing delay tho.

**Comment by Schamper** [comment] 2018-03-13 22:43
It's still slow on latest. My guess is that the file IO and importing adds a big overhead, while bytecode compiling and "exec"-ing is near instant (which is done also when importing, but now you skip expensive file IO). 
Don't have any example code lying around, but think of about 40-50 different structs that it will compile.

**Comment by arekbulski** [comment] 2018-03-14 00:39
The test suite compiles every class from the core library, and the entire test suite still takes only few seconds, so the overhead of compiling is negligible. Sorry, but I havent seen what you describe, not with recent code (since the cython was removed). You need to present a code sample that reproduces this overhead, because I havent encountered this in the test suite.

**Comment by arekbulski** [comment] 2018-03-14 10:30
On second thought, I will test the performance with your improvement and get back to you.

**Comment by arekbulski** [comment] 2018-03-14 12:19
Okay, I played a bit with your code and here is what I found out. The speedup is small, as far as I managed to measure it with the test suite, but it seems to me that this improvement is worthwhile nonetheless. For the record, I have an SSD. However, the patch works only on Python 3.4+, [test log](https://travis-ci.org/construct/construct/builds/353289604). I created a [branch](https://github.com/construct/construct/commits/patch-compilerimport) with your code. If you can manage to make it work on all runtimes, I will gladly merge it. 

I will gladly investigate other means of improving compilation delay, if you can suggest any. 

On side note, I should perhaps mention that the compiler works a bit differently in recent versions. It does not generate standalone modules anymore (that you can save and import in new process). It generates partial modules, which get linked with original instances. In other words, you need to recompile the constructs at each process restart. If you have a model where you spawn a process, compile a schema, use it once, and terminate the process, thats gonna add compiler ovearhead to each spawn. Compilation should only be used with constructs that are used milltions of times, or on megabyte data, per running process. I assume that this is not the case for you?

On another side note, I would like to stress out that PYPY achieves miracle performance (I dont mean the import delay). You can see the comparisons on [compiler page](https://construct.readthedocs.io/en/latest/compilation.html), bottom of the page. Just mentioning in case performance is important to you. There is pypy 3.5 as well.

**Comment by Schamper** [comment] 2018-03-14 18:56
Thanks, I'll play around with it and see if I can get a better example for you or improve it otherwise.

As for my use case, it's a fairly large and complex network protocol. Some parts of which really need high performance parsing, some don't. I have some wrappers around construct to make working with it a bit easier at times (specifically being able to more closely link "types"/structs with their data, either parsed or to-be build), which compiles by default. The obvious solution is to disable compiling for parts where it's not needed, but I figured it could still be an interesting issue to look into.

Regardless, I'll look into some possible performance optimisations.

**Comment by arekbulski** [comment] 2018-03-14 19:43
I merged your patch. The compiler uses it on supported runtimes, and reverts to older implementation (save to file, then import) otherwise. If you find additional means of improving the compiler, I will be happy to investigate those as well. As far as this issue is concerned, you can close the thread.

On side note, I would be interested in the extras code that you have (the helper code). Maybe it would be something worth adding as a feature?

**Comment by Schamper** [comment] 2018-03-14 20:50
I looked at why it doesn't work on Py2 (I don't have 3.3 installed, but judging from the tracebacks it's probably the same bug). What I think happens is that the global scope of the module is dropped because it goes out of the `compile` function scope and there are no further references to it. This can be checked by putting a debugger in `parseall` and dumping `globals()` (spoiler alert, everything is set to `None`.

This can be fixed by keeping a reference to the module somewhere. This can be either back on the `compiled` variable itself (`compiled.module = module` or something) or add it to sys modules like `sys.modules[modulename] = module`. Either way works and fixes the bug.

**Comment by arekbulski** [comment] 2018-03-15 01:17
Merged. That fixed the entire problem. Thank you much for your assisstance. I noticed the test suite runs about 0.5 second shorter (out of 6-7 seconds), that is actually within a margin of error, but it is a nice upgrade nonetheless. Did this improve much for you?

**Comment by Schamper** [comment] 2018-03-15 08:51
Yes, this actually brought it from seconds to near instant. I'll get back to you with example code if I can reproduce it easily, as well as with the other wrapper code I mentioned.

**Comment by arekbulski** [comment] 2018-03-15 10:33
Good, I think we can close the issue. If you find any additional ideas for improving the compiler, I will gladly consider it, but I dont think there is a real need to look for any? I suggest you close the ticket, and if you want to share some of the extras code then open a new ticket as feature request.

**Closed** 2018-03-15 10:52 UTC
Labels: enhancement, question
