### ISSUE TITLE
Use Container class with multiprocessing.Queue() 

### ISSUE THREAD

**Issue by kimpik** [construct/construct#249] opened 2016-10-14 21:55 UTC
Is the Container class supported in multiprocessing Queue? We have been using Container with the general Queue in a multithreading program.   Once the system was converted from multithreading to multiprocessing (which required multiprocessing.Queue), we can no longer get the Container instance from the multiprocessing.Queue(). 

Section of the reported error is shown here: 

``` py
  File "C:\Python27\python-2.7.4\lib\multiprocessing\queues.py", line 117, in get
    res = self._recv()
  File "C:\Python27\python-2.7.4\lib\site-packages\construct\lib\container.py", line 67, in __setitem__
    self.__keys_order__.append(key)
  File "C:\Python27\python-2.7.4\lib\site-packages\construct\lib\container.py", line 63, in __getattr__
    raise AttributeError(name)
AttributeError: __keys_order__
```

**Comment by harvimt** [comment] 2016-10-14 21:57
to use with multithreading.Queue it needs to be pickleable, that's probably the issue.

**Comment by arekbulski** [comment] 2016-10-14 22:05
Nothing in Construct is thread safe. If you want it to be, you probably need to figure it out yourself or give me a good example of how it fails. Can you show me some code that demonstrates the fail? Error messages is not enough.

**Comment by arekbulski** [comment] 2016-10-14 22:06
Nothing in Construct is thread safe. If you want it to be, you probably need to figure it out yourself or give me a good example of how it fails. Can you show me some code that demonstrates the fail? Error messages is not enough.

**Comment by harvimt** [comment] 2016-10-14 22:12
@arekbulski, notice that @kimpik is saying that it *works* just fine with threads (unsurprising because GIL), it fails with `multiprocessing` which requires things be pickelable.

Construct may need to support `__getstate__` and `__setstate__` on many of it's types for this to work.

**Comment by arekbulski** [comment] 2016-10-14 22:14
I think its only the Container that needs to be picklable, right? Parsing is done on thread? 

Please do not "at" me, its just clutter to my eyes.

**Comment by kimpik** [comment] 2016-10-14 22:15
Thanks. 
Here is my simple test program which flagged the same error. 
We put the Container on the Queue, and let the spawn process /thread to handle the parse/build operation. 


import multiprocessing
from construct import *


def worker(q):
    obj = q.get()
    print obj

if __name__ == '__main__':
    queue = multiprocessing.Queue()

    p = multiprocessing.Process(target=worker, args=(queue,))
    p.start()

    obj = Container(name="test")
    print obj
    queue.put(obj)

    # Wait for the worker to finish
    queue.close()
    queue.join_thread()
    p.join()

**Comment by arekbulski** [comment] 2016-10-14 22:17
Fix the code with triple ticks.

**Comment by kimpik** [comment] 2016-10-14 22:17
thanks!

**Comment by arekbulski** [comment] 2016-10-14 22:18
Fix the code with triple ticks. I see you are new to GitHub so just so you know, proper post formatting is expected of you.

**Comment by kimpik** [comment] 2016-10-14 22:20
Great. thanks for the tips!

**Comment by arekbulski** [comment] 2016-10-14 22:28
Imported your code into manual tests. Code throws following:
```py
$ python3 tests/manual_multiprocessing.py 
Container: 
    name = test
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/construct/lib/container.py", line 61, in __getattr__
    return self[name]
KeyError: '__keys_order__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "tests/manual_multiprocessing.py", line 6, in worker
    obj = q.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 113, in get
    return ForkingPickler.loads(res)
  File "/usr/local/lib/python3.5/dist-packages/construct/lib/container.py", line 67, in __setitem__
    self.__keys_order__.append(key)
  File "/usr/local/lib/python3.5/dist-packages/construct/lib/container.py", line 63, in __getattr__
    raise AttributeError(name)
AttributeError: __keys_order__

```

**Comment by kimpik** [comment] 2016-10-14 22:48
I am running Python v2.7.4. The Trace above is different than what I got but they are essentially reporting the same exception.

**Comment by arekbulski** [comment] 2016-10-14 22:50
Ahh pickling fails because Containers use attriute setting as putting a key. Unpickling works by assigning new attributes to a new object, which doesnt do what picker thinks. Yeah Mark was right.

**Comment by kimpik** [comment] 2016-10-14 23:15
Thanks for looking into this. That explains. 
We would try to work around this in the system code. 

Mark, thanks for your insight.

**Comment by arekbulski** [comment] 2016-10-14 23:35
Container code needs to be updated. I will fix it for you tomorrow. Good night.

**Comment by arekbulski** [comment] 2016-10-14 23:49
Mislicked uh? Happened to me too.

**Comment by kimpik** [comment] 2016-10-14 23:53
My subconscious told me that spot should be a "cancel" button. --> New to Github! Sorry!

**Comment by arekbulski** [comment] 2016-10-16 05:14
Pushed a fix. Try if HEAD not works and report back.

**Comment by arekbulski** [comment] 2016-10-16 11:20
You can test  that reverted commit but I have doubts it will work. Look at current code although that fails the testing so... I need help fixing it. Need assistance.

**Comment by domenzain** [comment] 2016-10-20 13:43
I currently work around this limitation by putting the raw unparsed bytes  into the `Queue` and parsing on the receiving side.

Clearly it would be more practical if Containers could be pickled in an official release.

**Comment by arekbulski** [comment] 2016-10-20 13:45
Of course. Also its worth noticing that parsing consumes quite some computing power so it may actually be more beneficial to parse on receiving side. So you might actually be doing it the right way already.

**Comment by kimpik** [comment] 2016-10-28 19:54
Thanks for the update.
However, I have rerun the test program "tests/manual_multiprocessing.py " again with the v2.8.8 release and still seeing the same error message as previously reported.  (running python v2.7.4)

```py
Container: 
    name = test
Process Process-1:
Traceback (most recent call last):
  File "C:\Python27\python-2.7.4\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\python-2.7.4\lib\multiprocessing\process.py", line 114, in run
worker running
    self._target(*self._args, **self._kwargs)
  File "D:\P4V\DEVWS\DEVS_FKL2_BRUCOMELA_DEV\src\_uxPrototype\construct_queue.py", line 7, in worker
    obj = q.get()
  File "C:\Python27\python-2.7.4\lib\multiprocessing\queues.py", line 117, in get
    res = self._recv()
  File "C:\Python27\python-2.7.4\lib\site-packages\construct\lib\container.py", line 95, in __setitem__
    self.__keys_order__.append(key)
  File "C:\Python27\python-2.7.4\lib\site-packages\construct\lib\container.py", line 91, in __getattr__
    raise AttributeError(name)
AttributeError: __keys_order__
```

**Comment by arekbulski** [comment] 2016-10-28 20:37
Use HEAD, fix might have not been released yet.

**Comment by arekbulski** [comment] 2016-10-29 12:09
Oh crap, fix was already in the last release. So this thing is still broken.

**Comment by arekbulski** [comment] 2016-10-29 13:12
Just pointing out again, for the record, when you distribute the parsed object across processes you are pickling it which means doing the reverse of the parsing that you just did. Multiprocessing on objects is counter productive, you should probably distribute the bytes? 

Also did you look at LazyStruct and other lazy equivalants? Does each node use all of the keys or does each use a subset?

**Comment by arekbulski** [comment] 2016-10-29 19:20
Since Containers implicitly should be picklable, I marked it as a bug.

**Comment by kimpik** [comment] 2016-10-31 14:12
In the original multi-threaded system, we dedicated one of the threads to handle the parse and build operations.    The parsed Container objects were passed to the application through a message Queue.  Likewise, multiple producers in the application would create Container objects and pass them to the Container parse/build thread through another message Queue.    To explore the possibility to optimize system performance, we tried to spin the Container parse/build processes in a separate process. 

Are you saying the pickling operations would likely use as much resources as the parsing operations?

**Comment by arekbulski** [comment] 2016-10-31 16:11
Not sure if it is same performance but it is same complexity. Depending on pickle implementation might be either way. My bet is on passing the bytes.

**Comment by arekbulski** [comment] 2016-10-31 16:51
This is what happens: it parses using construct, builds using pickle, parses using pickle. Won't ever be faster than just first parsing but it might be used to distribute the load away from congested node. Are we now on same page?

**Comment by arekbulski** [comment] 2016-11-01 03:55
Another reason is that I have totally no clue how to fix this thing. Seriously.

**Comment by domenzain** [comment] 2016-11-02 16:58
I'm working on a patch that fixes pickling (and therefore multiprocessing queues) for all Python versions in the continuous integration; as well as a couple of regression tests.

This comes in part due to the differences in how `pickle` deals with `dict` instances in Python 2 versus 3 (the default protocol is different).

**Comment by kimpik** [comment] 2016-11-02 17:42
Arkadiusz, thanks for the explanation. Very useful information!

**Comment by arekbulski** [comment] 2016-11-03 20:35
Should have been fixed by last PR.

**Comment by domenzain** [comment] 2016-12-02 09:55
On my end this works as expected with `Python 2.7.12` and `Python 3.5.2`
```py
$ python ./tests/manual_multiprocessing.py
Container: 
    name = test
Container: 
    name = test
(construct)  
$ workon construct3
(construct3)  
$ python ./tests/manual_multiprocessing.py
Container: 
    name = test
Container: 
    name = test
(construct3)  
```

**Comment by arekbulski** [comment] 2016-12-03 13:41
So the PR fix was successful. Kudos to you. :+1:

**Closed by arekbulski** 2016-12-03 13:41 UTC
Labels: bug found
