### ISSUE TITLE
construct 2.5.4 'unicode' does not have the buffer interface

### ISSUE THREAD

**Issue by joachimmetz** [construct/construct#89] opened 2016-09-06 06:24 UTC
It looks like the six removal changes have introduced another issue:
https://github.com/construct/construct/blame/master/construct/core.py#L298

(line numbers differ from the packaged release on pypi, including due to additional patches for #88)

```
======================================================================
ERROR: testMergeFromStorage (storage.zip_file.ZIPStorageFileWriterTest)
Tests the MergeFromStorage function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/storage/zip_file.py", line 1516, in testMergeFromStorage
    storage_writer.Close()
  File "./plaso/storage/zip_file.py", line 3077, in Close
    self._storage_file.Close()
  File "./plaso/storage/zip_file.py", line 2439, in Close
    self.Flush()
  File "./plaso/storage/zip_file.py", line 2497, in Flush
    self._WriteSerializedEventTags()
  File "./plaso/storage/zip_file.py", line 2087, in _WriteSerializedEventTags
    event_tag_index_table.Write()
  File "./plaso/storage/zip_file.py", line 903, in Write
    entry_data = self._TAG_INDEX_STRUCT.build(event_tag_index)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 218, in build
    self.build_stream(obj, stream)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 225, in build_stream
    self._build(obj, stream, Container())
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 709, in _build
    sc._build(subobj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 920, in _build
    case._build(obj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 709, in _build
    sc._build(subobj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 296, in _build
    self.subcon._build(self._encode(obj, context), stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 296, in _build
    self.subcon._build(self._encode(obj, context), stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 771, in _build
    sc._build(subobj, stream, context)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 406, in _build
    _write_stream(stream, self.lengthfunc(context), obj)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 319, in _write_stream
    stream.write(data)
TypeError: 'unicode' does not have the buffer interface
```

**Comment by joachimmetz** [comment] 2016-09-06 06:29
This might have already fixed by https://github.com/construct/construct/commit/646cdb899b4ecd7a6484215a116d20fd1b05b0c3. If so let me know and sorry for the dupe.

**Comment by joachimmetz** [comment] 2016-09-06 06:32
I think this might have been already addressed by post 2.5.4 changes. Please let me know, if so sorry for the dupe.

**Comment by arekbulski** [comment] 2016-09-06 09:18
Could you attach the Struct from that test? The issue is probably that string cons now require explicit encoding on py3. I will change that to utf8 default. Please wait a moment.

**Comment by joachimmetz** [comment] 2016-09-06 09:41
Sure, you can find the struct and code here: https://github.com/log2timeline/plaso/blob/master/plaso/storage/zip_file.py#L788

**Comment by arekbulski** [comment] 2016-09-06 10:54
Fixed the issue #87 , could have solved this one. Will be making a release in a moment. Look at #86 .

**Comment by joachimmetz** [comment] 2016-09-06 12:26
> Will be making a release in a moment

Great, thanks for the quick follow up.

**Comment by arekbulski** [comment] 2016-09-06 13:30
No problem. Please check if new release is still buggy and maybe close the issue.

**Comment by joachimmetz** [comment] 2016-09-06 18:41
Ack, I'll give the new version a try shorty.

**Comment by joachimmetz** [comment] 2016-09-06 19:21
To be verbose did you change the versions from 2.5.4 to 2.6.1 and 2.5.5 to 2.6.2 ?

**Comment by arekbulski** [comment] 2016-09-06 19:24
Correct. You can either revert to stable 2.5.3 or check out HEAD which is a bit ahead of latest beta release.

**Comment by joachimmetz** [comment] 2016-09-06 19:25
thx. I'll first give 2.6.2 a try and can always decide to switch back

**Comment by arekbulski** [comment] 2016-09-06 19:26
Then go for HEAD because pre-releases are no more stable than what you see in the trunk anyway. I put those out at random checkpoints.

**Comment by joachimmetz** [comment] 2016-09-06 19:30
ack, useful to know

**Comment by arekbulski** [comment] 2016-09-06 19:32
Look at #80 for what have been or is going to be changed.

**Comment by joachimmetz** [comment] 2016-09-06 19:34
thx, for all the hard work, good to see the new life in this project.

**Comment by joachimmetz** [comment] 2016-09-06 20:32
FYI hitting some other issues.

```
  File "/usr/lib/python2.7/dist-packages/construct/protocols/ipstack.py", line 67
    "0011508c283c001150886b570800450001e971474000800684e4c0a80202525eedda11"
                                                                           ^
SyntaxError: invalid syntax
```

**Comment by arekbulski** [comment] 2016-09-06 21:37
I started fixing some things in the examples code bfc756af05bd7d3fa58368359a335d4d9aa6fe9d but it still wont run.

The syntax is due to the fact that six.b(...) was removed so b"..." "..." is seen as b"..."+u"..." on PY3.

**Comment by joachimmetz** [comment] 2016-09-07 05:04
Ack, thx. Yeah I removed the b for now as a work around, but I'll switch back to 2.5.3 for now (also since I hit #92) and get back to 2.6.x testing when time permits. Feel free to resolve this issue since that seems to be fixed now.

**Closed** 2016-09-07 08:43 UTC
Labels: bug
