### ISSUE TITLE
Does this support calculating relative offsets?

### ISSUE THREAD

**Issue by mcscope** [construct/construct#664] opened 2018-02-19 10:13 UTC
Hey!
This is an awesome project! It adds a lot of missing functionality to Python. 
I'm building a database as a learning exercise, and I've run into a bit of a snag with it.

I'm trying to emulate the binary format that PostGres uses to store tables on disk. 
Here's a doc for it - https://www.postgresql.org/docs/10/static/storage-page-layout.html

My snag is on "ItemIdData" - this is an array of fixed length 4 byte pairs, which give the location of an individual record on the page.
This is useful so that only the records matching a given query need to be deserialized.  The records can be variable length, so an offset - table is needed. 

Okay, so here's my attempt to recreate this in Construct.
```
RatingConstruct = NamedTuple("Rating",
                             "userId movieId rating timestamp",
                             Int16ub >> Int16ub >> Float32b >> Int32ub
                             )

RecordHeader = Struct(
    "transaction" / Int16ub,
    "bitfield" / Int16ub,
)

Record = Struct(
    "offset" / Tell,
    "header" / RecordHeader,
    "record" / RatingConstruct,
)

Page = Struct(
    "count" / Rebuild(Byte, len_(this.records)),
    "records" / Record[:],
    "proof_weve_already_built" / Tell,
    # TODO line pointers would be nice. but how to do in Construct?
    'record_pointers' / Rebuild(Array(this.count, Int16ub),
                                lambda this: [r['offset'] for r in this.records]),
)
```

so unfortunately, I get an error on that last line... 
```
Traceback (most recent call last):
  File "tmp.py", line 61, in <module>
    page = Page.build({"records": ratings_w_headers})
  File "/Users/Christopher/Code/bradfield/databases/redstreak/env/lib/python3.6/site-packages/construct/core.py", line 287, in build
    self.build_stream(obj, stream, **kw)
  File "/Users/Christopher/Code/bradfield/databases/redstreak/env/lib/python3.6/site-packages/construct/core.py", line 303, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/Users/Christopher/Code/bradfield/databases/redstreak/env/lib/python3.6/site-packages/construct/core.py", line 1903, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/Users/Christopher/Code/bradfield/databases/redstreak/env/lib/python3.6/site-packages/construct/core.py", line 2363, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/Users/Christopher/Code/bradfield/databases/redstreak/env/lib/python3.6/site-packages/construct/core.py", line 2587, in _build
    obj = self.func(context) if callable(self.func) else self.func
  File "tmp.py", line 37, in <lambda>
    lambda this: [r['header']['offset'] for r in this.records]),
  File "tmp.py", line 37, in <listcomp>
    lambda this: [r['header']['offset'] for r in this.records]),
KeyError: 'offset'
```

I'm tracking it down by putting a print statement in that lambda, and printing out the entirety of `this`.
```
Container:
    records = [{'header': {'transaction': 3, 'bitfield': 0}, 'record': Rating(userId=1, movieId=2, rating=3.5, timestamp=1112486027)}, {'header': {'transaction': 3, 'bitfield': 0}, 'record': Rating(userId=1, movieId=29, rating=3.5, timestamp=1112484676)}, {'header': {'transaction': 3, 'bitfield': 0}, 'record': Rating(userId=1, movieId=32, rating=3.5, timestamp=1112484819)}, {'header': {'transaction': 3, 'bitfield': 0}, 'record': Rating(userId=1, movieId=47, rating=3.5, timestamp=1112484727)}, {'header': {'transaction': 3, 'bitfield': 0}, 'record': Rating(userId=1, movieId=50, rating=3.5, timestamp=1112484580)}]
    count = 5
    proof_weve_already_built = 81
    record_pointers = None
```
So at this point, it seems like Count has already been rebuilt, but records hasn't been changed to it's final version - it's still what I passed in.   There's no offset there yet - the tell. 

If I put a tell in the Page object itself, the top level object, I can see THAT tell, even if it's after records.
For that tell to exist, the binary size must have already been calculated so the offsets of the record children could have been calculated too.  So, perhaps it's a question of scope?

The tell 'proof we've already built' means that... I believe the subcons have already been built, right? But I'm not seeing the built/parsed version. I'd hope to see the container with all sub-containers fully built with 'tells', so that I can calculate my offsets perfectly. 

This package is complicated enough that I wonder if I'm missing something, or if this is impossible to do right now in construct. What do you think?

PS. In postgres the line pointers appear earlier in the page than the actual records. I think construct calculates from top to bottom, preserving order, so I figured this would only be possible if the line pointers are last. What do you think?

PPS I suppose as a last resort, I could pre-render just the records, then read the tells and somehow pass them in to the page object pre-rendered?

**Comment by arekbulski** [comment] 2018-02-19 11:00
I think the issue is trivial and you just missed some sleep. :slightly_smiling_face: The "offset" exists in Record but perhaps should be in RecordHeader. Doesnt matter which because both are at same offset. Either move it, or change lambda:
```py
lambda this: [r.header.offset for r in this.records]),
lambda this: [r.offset for r in this.records]),
```

Its correct that Structs build members in top-to-bottom order, but you can always use fields that produce data from other sources than stream (like Computed) or that access stream at random locations (like Pointer). The order of Pointers in your struct is only important in the sense that one field may need offsets taken from another field. Just that.

Neither from your description or from linked docs, I cannot tell if 4 bytes is the size of (offset,length) pair or the size of whatever offset points to. Unclear language in specs.

[Timestamp](https://construct.readthedocs.io/en/latest/api/misc.html#construct.Timestamp) class was recently added (like yesterday).

**Comment by mcscope** [comment] 2018-02-19 11:20
Sorry, I was moving offset around to see if it mattered, so I think my code had it in the wrong place.  No matter which place I put it, if I print out the records in the lambda (a neat trick), I don't see the offsets anywhere. 

I stepped through the _build function with a debugger and looks like when it tries to call _build on the records subcon, it returns None, so it doesn't update the current context. 
That means that when the record pointers go to look at it, it sees the version before offsets. 


You are really correct about the sleep though. Maybe I'll look at this tomorrow and see the answer, or at least have the mental capacity to figure out the significance of returning None from _build. 


Re the postgres docs - 4 bytes is the size of the pointer. The actual item it points too is an entire database row (called Tuples in the docs).  They can be quite long, and have variable length, so the offset +length lets you just get the one you want.

**Comment by mcscope** [comment] 2018-02-19 11:26
Oooooh looks like GreedyRanges just don't return any context from their _build. 
![image](https://user-images.githubusercontent.com/3921648/36375553-9028fc22-1524-11e8-8164-b7f78ee43cab.png)
Should there be a list that accumulates the subcon _build's here and then returns it?

**Comment by arekbulski** [comment] 2018-02-19 13:26
Yes and no. Indeed its a bug related to repeater-category classes and Rebuild. When I was implementing the build-retvalue infrastructure, I got a bit sloppy. The semantics (then and now) is that Struct checks _build retvalue, and replaces context entry WHEN its None. The repeater classes would return a list like [None, None, ...] which is not None, therefore would override context entry with nonsense. To fix this, all classes will need to be updated to return original obj (instead of None) and Struct to override context unconditionally. I am promoting this to bug status and top priority.

Re docs, if the offset is 32bits then why are you using 16bit fields in your code?

**Comment by mcscope** [comment] 2018-02-19 21:11
Great! So it's a legit bug. 
I might end up patching this locally sometime this week so that I can use it for my database. 
If I do, should I submit it to this project as a PR?  I _think_  I just need to patch GreedyRange for my own use. How much more effort would it be to make it work globally?
(How many other classes would need to be updated?) I'll write the global solution if it's not far out of my way. :-)

The postgres line pointers are offset and length. I'll probably get both but I ran into this roadblock on offset before I could get to length.   This format is actually for my own database that I'm building as a learning exercise, so it doesn't need to mimic postgres exactly, but I am using them as a guide. 


PS thank you so much for maintaining this project and being so responsive!

**Comment by arekbulski** [comment] 2018-02-20 15:40
Bug was fixed in ed5a4985969209ca9a73d622890efb280dd4e976. You can pull upstream or just wait a day until it gets shipped to pypi.

**Comment by arekbulski** [comment] 2018-02-20 21:09
Bug was fixed in ed5a4985969209ca9a73d622890efb280dd4e976 and shipped.

**Comment by mcscope** [comment] 2018-02-21 02:12
👏 👏 👏👏 👏 👏👏 👏 👏
 👍  Wow you work fast! 👍 
👏 👏 👏👏 👏 👏👏 👏 👏
I'll pull the latest. Thank you!

**Closed** 2018-02-21 04:53 UTC
Labels: bug found, question

**Comment by arekbulski** [comment] 2018-02-21 04:55
Request on the side, could you post your entire code (assuming its MIT licence) under #630 ? I might add it to the gallery or use it as reference when writing another.

**Comment by mcscope** [comment] 2018-03-08 22:31
@arekbulski I posted over there. Use it however you'd like
