### ISSUE TITLE
sizeof fails for a Struct containing a Switch over Structs containing variable size data

### ISSUE THREAD

**Issue by catern** [construct/construct#409] opened 2017-10-20 18:19 UTC
```
myproto_event = Struct(
    "len" / Rebuild(Int16ul, len_(this.data)),
    "data" / Byte[this.len],
)

myproto_packet = Struct(
    "event_type" / Byte,
    "event" / Switch(this.event_type, {
        0: myproto_event,
    }),
)

myproto_packet.sizeof(myproto_packet.parse(bytes(100)))
```

Resulting error:

```
Traceback (most recent call last):
  File ".../python3.5/site-packages/construct/core.py", line 1078, in _sizeof
    min = self.min(context) if callable(self.min) else self.min
  File ".../python3.5/site-packages/construct/expr.py", line 146, in __call__
    return context2[self.__name]
KeyError: 'len'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../python3.5/site-packages/construct/core.py", line 2800, in _sizeof
    return self.subcon._sizeof(context, path)
  File ".../python3.5/site-packages/construct/core.py", line 1081, in _sizeof
    raise SizeofError("cannot calculate size, key not found in context")
construct.core.SizeofError: cannot calculate size, key not found in context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.5/site-packages/construct/core.py", line 226, in sizeof
    return self._sizeof(context, "sizeof")
  File ".../python3.5/site-packages/construct/core.py", line 916, in _sizeof
    return sum(sc._sizeof(nest(context, sc), path) for sc in self.subcons)
  File ".../python3.5/site-packages/construct/core.py", line 916, in <genexpr>
    return sum(sc._sizeof(nest(context, sc), path) for sc in self.subcons)
  File ".../python3.5/site-packages/construct/core.py", line 2800, in _sizeof
    return self.subcon._sizeof(context, path)
  File ".../python3.5/site-packages/construct/core.py", line 1607, in _sizeof
    return sc._sizeof(context, path)
  File ".../python3.5/site-packages/construct/core.py", line 916, in _sizeof
    return sum(sc._sizeof(nest(context, sc), path) for sc in self.subcons)
  File ".../python3.5/site-packages/construct/core.py", line 916, in <genexpr>
    return sum(sc._sizeof(nest(context, sc), path) for sc in self.subcons)
  File ".../python3.5/site-packages/construct/core.py", line 2804, in _sizeof
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.SizeofError: cannot calculate size, key not found in context
    sizeof -> event -> data
```

The issue appears to be that Struct._sizeof uses this code to detect structs and enter nested contexts:
```
            def isStruct(sc):
                return isStruct(sc.subcon) if isinstance(sc, Renamed) else isinstance(sc, Struct)
```

which fails to detect a Struct inside a Switch.

This only fails when the nested Struct contains variable size data, because only then does that Struct need to actually look at its context.

**Comment by arekbulski** [comment] 2017-10-25 18:59
Sizeof() is usually called without args. I have no idea why anyone would provide parsed dict as context to sizeof. Therefore this line is suspicious:
```py
myproto_packet.sizeof(myproto_packet.parse(bytes(100)))
```

**Comment by catern** [comment] 2017-10-25 19:49
If I want to determine the size of a constructor, how would I usually generate a context to pass it?

**Comment by arekbulski** [comment] 2017-10-26 13:55
Usually you just call Sizeof() without args.

**Comment by catern** [comment] 2017-10-26 14:00
Yes, but if the constructor is variable size?

**Comment by arekbulski** [comment] 2017-10-26 23:55
Struct.Sizeof() without args means it will START with empty context but as each subcon gets parsed, their values will be inserted into the context dict.

**Comment by catern** [comment] 2017-10-27 17:32
I'm sorry, I guess I don't understand. If we're talking about Struct.sizeof(), with no arguments, then what is being parsed to populate the context with values? There is nothing there to parse, as far as I can see?

Concretely:
```
myproto_event = Struct(
    "len" / Rebuild(Int16ul, len_(this.data)),
    "data" / Byte[this.len],
)
```
What should I call to determine the size of this constructor? How should I call it? If I called "myproto_event.sizeof()" I would get an error.

**Comment by arekbulski** [comment] 2017-10-27 19:26
Sizeof() in general is to be used not in context of specific data but to measure fixed-sized constructs. If to measure the size you need the data bytes then you aleady have what you need to lenght it.

Also the Struct you are presenting looks exactly like Prefixed/PrefixedArray class.

**Comment by catern** [comment] 2017-10-29 23:40
What is the use case for calling sizeof with an argument, then?

**Comment by arekbulski** [comment] 2017-10-30 14:09
So you can explicitly provide context values (instead of depending on other Struct subcons to produce those values during parsing). 
```py
In [5]: st = Struct("optional"/If(this.found, Byte))

In [6]: st.sizeof(found=1)
Out[6]: 1

In [7]: st.sizeof(found=0)
Out[7]: 0
```

**Comment by arekbulski** [comment] 2017-10-30 14:14
I was trying to point out that you should use Prefixed instead.

**Comment by catern** [comment] 2017-10-30 17:23
Okay, but... how do I know what context values to provide? With many big opaque variable-size structs, I don't want to have to maintain knowledge about what context values are needed.

I know that my example is identical to Prefixed, it was just an example. :) My real use case is not identical to Prefixed.

Let me be more concrete. I have a large message structure `A` containing multiple variable-sized fields. The header at the very start of the message, contains a "size" field which is supposed to contain the size of the entire message. Currently I am using `"size" / Rebuild(construct.Int16ul, lambda ctx: A.sizeof(ctx)` to fill in this size field. Is this an acceptable use of sizeof? How else should I determine the size of the entire struct, from with the struct?

Sorry for all the meandering questions. :)

**Comment by arekbulski** [comment] 2017-10-30 18:08
I have never seen this kind of lambda, no idea what it will do. But more to the point, If you have subcons whos size depends on particular data, then you need to parse a partiticular bytes to know the size, but if you have the bytes then you already knw its lenght. I am not even sure what you are trying to do here.

**Comment by catern** [comment] 2017-10-30 18:22
If I already have the bytes, then yes, of course I already know their length. 

But I'm talking about when I build some bytes, from some dictionary as input. In that case, I don't know the length of the resulting bytes without building them. But I can't build those bytes without knowing the length, because there is a field in this protocol which must contain the length of the message. It seems like sizeof() is exactly what I should be using here. Does that make sense?

**Comment by arekbulski** [comment] 2017-10-30 18:27
Ah yes, you make perfect sense now. Sizeof is appropriate for that.

**Comment by catern** [comment] 2017-10-30 20:41
OK, so, getting back to the issue, here is an instance of doing what I just described:

```
myproto_event = Struct(
    "len" / Rebuild(Int16ul, len_(this.data)),
    "data" / Byte[this.len],
)

myproto_packet_works = Struct(
    "size" / Rebuild(construct.Int16ul, lambda ctx: myproto_packet_works.sizeof(ctx)),
    "event_type" / Byte,
    "event" / myproto_event,
)

myproto_packet_works.build({"event_type": 0, "event": {"len": 0, "data": bytes()}})
```

This works just fine.

However, if I nest `myproto_event` inside a Switch:
```
myproto_packet_fails = Struct(
    "size" / Rebuild(construct.Int16ul, lambda ctx: myproto_packet_fails.sizeof(ctx)),
    "event_type" / Byte,
    "event" / Switch(this.event_type, {
        0: myproto_event,
    }),
)

myproto_packet_fails.build({"event_type": 0, "event": {"len": 0, "data": bytes()}})
```

This fails with the exception in the my original issue. I think that is a bug?

**Comment by arekbulski** [comment] 2017-12-06 18:33
Frankly, I have no idea. Switch is a horrific class that I dont understand how it works. It caused more problems that it solved. It was in the 2.5 version when I took over the project, and it somehow remained. Or rather survived the 2.8 cleanup. Its not a bug if you put a blob into a magic fuckin box and get a funny looking rabbit as result.

**Closed by arekbulski** 2017-12-06 18:33 UTC
Labels: question

**Comment by catern** [comment] 2017-12-07 16:51
But, I mean... how else is one supposed to parse tagged unions, other than with Switch?

**Comment by arekbulski** [comment] 2017-12-08 02:40
There is a `Union` class too.

**Comment by catern** [comment] 2017-12-10 14:57
AFAICT, Union doesn't work if you have fields after that Union? Also, with Union you have to implement the switch on the tag yourself in Python code. For me, not having to manually implement switching on the tag in tagged unions is the main reason I'm using a binary parsing library.

**Comment by arekbulski** [comment] 2017-12-10 15:06
Have you looked into RawCopy class?

**Comment by catern** [comment] 2017-12-11 16:59
Yes, I've looked and tried to use it a fair bit for some other unrelated use cases. But I don't understand how it's useful for this use case (parsing a tagged union, avoiding manually switching on the tag), can you explain?

**Comment by arekbulski** [comment] 2017-12-11 17:10
RawCopy provides you with length of bytes data, to use instead of sizeof(...).

**Comment by arekbulski** [comment] 2017-12-19 17:44
Since those lenghtfields are fixed length, I would build a struct with fake len value, measure the bytes that came out, build second time with that value.

**Comment by catern** [comment] 2017-12-20 14:54
That's effectively what sizeof does. Why can't we just fix sizeof to work with switch, rather than hacking around the problem?

**Comment by arekbulski** [comment] 2017-12-20 15:25
PR if you know what is the problem and how to fix it

**Comment by catern** [comment] 2017-12-20 21:39
I do know what the problem is (it's the isStruct code I mentioned in the original issue), but I got the impression you didn't think it was a bug. If I fix it, you'll accept the PR?

**Comment by arekbulski** [comment] 2017-12-20 22:30
I promise to consider it, but I need to see the code to know.
