### ISSUE TITLE
Using IntEnum as keys with Switch doesn't parse correctly

### ISSUE THREAD

**Issue by rmcgregor1990** [construct/construct#844] opened 2020-03-04 17:05 UTC
Hey, it seems using python stdlib IntEnums with Switches doesn't match as you would expect when parsing.

Example under python 3.8:
```python
import enum
from construct import Struct, Switch, Enum, Int8ub, this, GreedyBytes, Int16ub


class Key(enum.IntEnum):
    X = 0
    Y = 1
    Z = 2


broken_foo = Struct(
    "key" / Enum(Int8ub, Key),
    "payload" / Switch(this.key, {
        Key.X: Int16ub,
        Key.Y: Int8ub,
    }, default=GreedyBytes)
)


encoded = broken_foo.build({"key": Key.Y, "payload": 23})

decoded = broken_foo.parse(encoded)
print("broken:", decoded)


print()

working_foo = Struct(
    "key" / Enum(Int8ub, X=0, Y=1, Z=2),
    "payload" / Switch(this.key, {
        "X": Int16ub,
        "Y": Int8ub,
    }, default=GreedyBytes)
)

encoded = working_foo.build({"key": "Y", "payload": 23})

decoded = working_foo.parse(encoded)
print("working:", decoded)
```

Prints out:
```
$ python example.py 
broken: Container: 
    key = (enum) Y 1
    payload = b'\x17' (total 1)

working: Container:
    key = (enum) Y 1
    payload = 23
```
I would expected these two ways of using Enums to be equivalent.

Cheers,
Rob

**Comment by rmcgregor1990** [comment] 2020-03-04 22:08
So this seems to be due to way enums are stored internally, the IntEnum member in converted into a EnumIntegerString which subclasses str. Which means the Switch lookup doesn't work as its comparing a IntEnum member (which subclasses int) to EnumIntegerString  (which subclasses str). Hence the parse lookup fails and it does the default.

This can be fixed by using a key callable and explicitly converting to an int.

```python
broken_foo = Struct(
    "key" / Enum(Int8ub, Key),
    "payload" / Switch(lambda this: int(this.key), {    # casting allows correct int to int comparisons
        Key.X: Int16ub,
        Key.Y: Int8ub,
    }, default=GreedyBytes)
)
```
Is this intended behavior? Or is using IntEnums outside of the Enum construct just not supported?

**Comment by arekbulski** [comment] 2020-03-05 07:00
Well, you got me there. Is this intended behavior? No. Is it a bug? Naaaah... lets say it is not. The whole functionality of using Enum34 is crap and should have never been implemented in the first place. The "right way" of writing it is the one that works correctly. I will add your examples to the test suite but wont be fixing it in the core library.

**Closed** 2021-01-27 14:20 UTC
Labels: bug found
