### ISSUE TITLE
Trying to read binary file in utf8? - Failing in Python3

### ISSUE THREAD

**Issue by latot** [construct/construct#517] opened 2018-01-28 00:00 UTC
Hi all!, i'm here again, testing and testing, i found this, i don't know if is a problem in the code or in the lib, the weird here is, the code works fine in Python2, i can execute, use all, anyway there no problem, but now i test it with Python3, and show an error, i have no idea why, here the outputs:

I test this with the nepugia project, i test it with 2 differents files, and 2 differents type of error, but can be the same.

Python3.4 3.5 and 3.6
```
>>> with open(os.path.join(d, 'stitem.gbin')) as item_file:
...     item_db = GBNLFormat(ItemModel).parse_stream(item_file)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 169, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 1222, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 874, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 2111, in _parse
    stream.seek(offset, 2 if offset < 0 else 0)
io.UnsupportedOperation: can't do nonzero end-relative seeks
>>> with open(os.path.join(d, 'strsystem.gstr')) as system_file:
...     system_db = GSTLFormat.parse_stream(system_file)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 169, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 874, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 1222, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 874, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 1281, in _parse
    obj = self.subcon._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 398, in _parse
    return _read_stream(stream, length)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 65, in _read_stream
    data = stream.read(length)
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 24: invalid start byte
```

Python 2.7 (All working :D)
``` 
>>> with open(os.path.join(d, 'stitem.gbin')) as item_file:
...     item_db = GBNLFormat(ItemModel).parse_stream(item_file)
... 
>>> with open(os.path.join(d, 'strsystem.gstr')) as system_file:
...     system_db = GSTLFormat.parse_stream(system_file)
... 
>>>
```

Thx.

**Comment by arekbulski** [comment] 2018-01-28 00:24
Hmm would you be able to obtain and show me the actual bytes that are read by the String construct? I would also like to see the construct itself, a link to a particular line. 

Use RawCopy to obtain the bytes, or insert Probe in the struct just before the string field, or better do both. RawCopy will show only the bytes that were read, Probe will peek further (128 bytes) into the stream. Check the tutorial docs how to use them. 

On side note, string classes have huge problems with UTF16 UTF32 encodings but UTF8 should work without any issues.

**Comment by latot** [comment] 2018-01-28 00:55
Hi!, mm, i'm testing this simpler, this code have the same effect, works in python2 but fails in python3:

```
with open(os.path.join(d, 'stitem.gbin')) as item_file:
 RawCopy(Byte).parse_stream(item_file)
```

out of python2:
```
Container(length=1)(offset2=1)(data='\x01')(offset1=0)(value=1)
```

out of python3:
```
Traceback (most recent call last):
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 505, in _parse
    data = _read_stream(stream, self.sizeof())
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 65, in _read_stream
    data = stream.read(length)
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 146: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 169, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 2383, in _parse
    obj = self.subcon._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 508, in _parse
    raise FormatFieldError("packer %r error during parsing" % self.fmtstr)
construct.core.FormatFieldError: packer '>B' error during parsing
```

now, how we can't get the data i run this in python2 to read the byte in the position of the error:

 ```
>>> with open(os.path.join(d, 'stitem.gbin')) as item_file:
...  RawCopy(Seek(145) >> Byte).parse_stream(item_file)
... 
Container(length=146)(offset2=146)(data='\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')(offset1=0)(value=[None, 0])
```

Running this in python3 we get the same error in pos1 (the last \x00)

Thx.

**Comment by latot** [comment] 2018-01-28 00:57
we like logs?

```
>>> with open(os.path.join(d, 'stitem.gbin')) as item_file:
...  RawCopy(Seek(145) >> Byte).parse_stream(item_file)
... 
Traceback (most recent call last):
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 505, in _parse
    data = _read_stream(stream, self.sizeof())
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 65, in _read_stream
    data = stream.read(length)
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 169, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 2383, in _parse
    obj = self.subcon._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 967, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/pipe/.local/lib64/python3.6/site-packages/construct/core.py", line 508, in _parse
    raise FormatFieldError("packer %r error during parsing" % self.fmtstr)
construct.core.FormatFieldError: packer '>B' error during parsing
```

**Comment by arekbulski** [comment] 2018-01-28 01:11
For a moment I thought, holy shit, are you telling me that Byte.parse(bytes(1)) is failing?

You are opening the file implicitly in text mode, right?... :grin:

**Comment by arekbulski** [comment] 2018-01-28 05:51
Simple, your declaration probably has "GBNL" instead of b"GBNL". On PY3 unprefixed string is treated as unicode, not bytes. Use b- and u- prefixes in declarations explicitly.

**Comment by latot** [comment] 2018-01-28 05:56
or..., now i need to write all the strings as binary in the structs, that is my bad...
(this mix of things)

well, i think with this issue this will be fixed:
https://github.com/construct/construct/issues/522

is possible check this type of things?, as i remember the function ```String```, check if the input is binary and send an error.

Thx! Cya.

**Comment by arekbulski** [comment] 2018-01-28 06:22
Regarding text file:
I added #522 after your question. Only now I realized that I had someone the same problems before, years ago. It seems that (1) people still use PY2 which is ancient dinosaur, (2) people dont quite seem to grasp PY2/3 differences like bytes/unicode. Its easy to check.

Regarding Const:
I could have Const (and some other classes) check if its unicode and raise an error. However... I must blatantly point out that the problem is mostly in you not understanding Python (official Library Reference is superb) and you not undersanding Construct semantics (I spent much time writing the docs). It took me about one second from looking at the exceptions. "data" is not b"data". Check can be implemented but gets lowest priority. #524 No problem asking, so no worries.

**Comment by arekbulski** [comment] 2018-01-28 23:43
@latot 
I implemented Const check, it will be included in next release. 

Unfortunately its not possible to check if a stream is in text mode or binary mode, other than just reading from it.

**Comment by arekbulski** [comment] 2018-01-29 00:56
@latot 
Added 2 warnings in docs related to your issues
https://construct.readthedocs.io/en/latest/advanced.html#strings
https://construct.readthedocs.io/en/latest/advanced.html#processing-files-or-data

**Comment by latot** [comment] 2018-01-29 01:11
:O Thx!

only an idea, maybe to try check the stream, read the first bite and check if is in binary mode?

**Comment by arekbulski** [comment] 2018-01-29 01:15
That would be a wrong way to go about it.

**Comment by arekbulski** [comment] 2018-01-29 02:19
Look at #527

**Closed** 2018-01-29 02:19 UTC
Labels: enhancement, question

**Comment by latot** [comment] 2018-01-29 04:25
Thx!
