### ISSUE TITLE
A checksum which depends on fields before and after it

### ISSUE THREAD

**Issue by HL94DXU** [construct/construct#679] opened 2018-03-04 22:56 UTC
Suppose I have a binary file format with the following structure:
`my_struct = Struct(
    "field1" / ???,
    "checksum" / Bytes(64),
    "field2" / ???
  )`

The types are arbitrary, and in reality field1 & field2 are a multitude of different fields, but the important point is that there is a checksum field in the middle of the struct, and it is a function of both the fields before it and after it.

Is there a convenient way to calculate a checksum field like this?  
I've seen the Checksum construct, but I think that it allows you to take into the calculation only fields which appear before the checksum field.  
Also, I'm not sure how you would pass to Checksum a mix of different fields in an arbitrary order (as I said, the actual struct has many fields).

Thank you.

**Comment by yannayl** [comment] 2018-03-04 22:58
Maybe using Pointer you can specify it only in the end. Not sure

**Comment by arekbulski** [comment] 2018-03-05 02:58
I assume you are asking about building (not parsing).

Correct, the Checksum class does work (effectively) only with fields preceding it. But that is not entirely true. The Struct does insert all items into the context at the beginning. The problem is, even if you wrap both fields using RawCopy, they wont be processed into byte representation until they are built into the stream. Example:
```
>>> d = Struct(
...     Probe(),
...     "fields" / RawCopy(Struct("num"/Byte)),
...     Probe(),
... )
>>> d.build(dict(fields=Container(value=Container(num=1))))
--------------------------------------------------
Probe, path is (building), into is None
Container: 
    field2 = Container: 
        value = Container: 
            num = 1
--------------------------------------------------
--------------------------------------------------
Probe, path is (building), into is None
Container: 
    field2 = Container: 
        value = Container: 
            num = 1
        data = b'\x01' (total 1)
        offset1 = 0
        offset2 = 1
        length = 1
--------------------------------------------------
```
I am already aware of this limitation, but I dont think it can be fixed without completely changing the semantics of Struct building, which would be problematic.

The suggestion to use Pointer is pretty good. In fact, there are many formats where the checksum is at the beginning and covers further fields. They do it by building the blob (inserting 0 as checksum), hashing the bytes, and then rewriting that one checksum field. Thats exactly what Pointer does.
```
>>> import hashlib
>>> d = Struct(
...     "offset" / Tell,
...     "checksum" / Padding(64),
...     "fields" / RawCopy(Struct(
...         Padding(1000),
...     )),
...     "checksum" / Pointer(this.offset, Checksum(Bytes(64), 
...         lambda data: hashlib.sha512(data).digest(), 
...         this.fields.data)),
...     Probe(),
... )
>>> d.build(dict(fields=dict(value={})))
--------------------------------------------------
Probe, path is (building), into is None
Container: 
    fields = Container: 
        value = Container: 
        data = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, to)
        offset1 = 64
        offset2 = 1064
        length = 1000
    offset = 0
    checksum = b"\xca=\xffa\xbb#Gz\xa6\x08{'P\x82d\xa6"... (truncated, total 64)
--------------------------------------------------
```
Note that two fields are named checksum. This is to overwrite the context entry with the actual checksum. The first checksum field could be unnamed, but I think its readble that way.

**Comment by arekbulski** [comment] 2018-03-07 14:10
Checksum class docs, for reference:
https://construct.readthedocs.io/en/latest/api/tunneling.html#construct.Checksum

**Closed** 2018-03-08 10:40 UTC
Labels: question
